### ISSUE TITLE
No OpKernel was registered to support Op 'AuctionMatch'

### ISSUE THREAD

**Issue by ShreyasSkandan** [epiception/CalibNet#8]
I'm trying to train your network using the script mentioned in the README. I'm getting the follow error:

```
Caused by op u'AuctionMatch_1', defined at:
  File "train_model_combined.py", line 87, in <module>
    cloud_loss_validation = model_utils.get_emd_loss(cloud_pred, cloud_exp)
  File "/data/Docker_Codebase/CalibNet/code/model_utils.py", line 42, in get_emd_loss
    matchl_out, matchr_out = tf_auctionmatch.auction_match(pred, gt)
  File "/data/Docker_Codebase/CalibNet/code/tf_ops/emd/tf_auctionmatch.py", line 20, in auction_match
    return auctionmatch_module.auction_match(xyz1,xyz2)
  File "<string>", line 37, in auction_match
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op AuctionMatch with these attrs.  Registered devices: [CPU], Registered kernels:
  device=GPU
         [[Node: AuctionMatch_1 = AuctionMatch[](map_1/TensorArrayStack_1/TensorArrayGatherV3, map_2/TensorArrayStack_1/TensorArrayGatherV3)]]
```

I'm using CUDA8.0, Tensorflow 1.3.0 and Python2.7 as mentioned in the README.

**Comment by krrish94** [comment]
This is a Tensorflow 1.3 issue. You absolutely need to use an older version. Tensorflow 1.2 will solve this for you.

**Comment by ShreyasSkandan** [comment]
I just tried this with Tensorflow 1.2.0 and it still does not work.

**Comment by ShreyasSkandan** [comment]
Full output:

```
root@853a62860973:/data/Docker_Codebase/CalibNet/code# CUDA_VISIBLE_DEVICES=1 python -B train_model_combined.py
('layer0', TensorShape([Dimension(5), Dimension(94), Dimension(311), Dimension(64)]))
('layer_1_1_1', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(64)]))
('layer_1_1_2', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(64)]))
('layer_1_2_1', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(64)]))
('layer_1_2_2', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(64)]))
('layer_2_1_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(128)]))
('downsample_layer_2_1_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(128)]))
('layer_2_1_2', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(128)]))
('layer_2_2_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(128)]))
('layer_2_2_2', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(128)]))
('layer_3_1_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(256)]))
('downsample_layer_3_1_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(256)]))
('layer_3_1_2', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(256)]))
('layer_3_2_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(256)]))
('layer_3_2_2', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(256)]))
('layer_4_1_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(512)]))
('downsample_layer_4_1_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(512)]))
('layer_4_1_2', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(512)]))
('layer_4_2_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(512)]))
('layer_4_2_2', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(512)]))
('layer0', TensorShape([Dimension(5), Dimension(94), Dimension(311), Dimension(32)]))
('layer_1_1_1', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(32)]))
('layer_1_1_2', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(32)]))
('layer_1_2_1', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(32)]))
('layer_1_2_2', TensorShape([Dimension(5), Dimension(47), Dimension(156), Dimension(32)]))
('layer_2_1_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(64)]))
('downsample_layer_2_1_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(64)]))
('layer_2_1_2', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(64)]))
('layer_2_2_1', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(64)]))
('layer_2_2_2', TensorShape([Dimension(5), Dimension(24), Dimension(78), Dimension(64)]))
('layer_3_1_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(128)]))
('downsample_layer_3_1_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(128)]))
('layer_3_1_2', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(128)]))
('layer_3_2_1', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(128)]))
('layer_3_2_2', TensorShape([Dimension(5), Dimension(12), Dimension(39), Dimension(128)]))
('layer_4_1_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(256)]))
('downsample_layer_4_1_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(256)]))
('layer_4_1_2', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(256)]))
('layer_4_2_1', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(256)]))
('layer_4_2_2', TensorShape([Dimension(5), Dimension(6), Dimension(20), Dimension(256)]))
Here
Here
2018-11-30 16:40:02.182564: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-30 16:40:02.182593: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-30 16:40:02.182600: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-30 16:40:02.182604: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-30 16:40:02.182609: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train_model_combined.py", line 105, in <module>
    sess.run(tf.global_variables_initializer())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'AuctionMatch' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: AuctionMatch_1 = AuctionMatch[](map_1/TensorArrayStack_1/TensorArrayGatherV3, map_2/TensorArrayStack_1/TensorArrayGatherV3)]]

Caused by op u'AuctionMatch_1', defined at:
  File "train_model_combined.py", line 87, in <module>
    cloud_loss_validation = model_utils.get_emd_loss(cloud_pred, cloud_exp)
  File "/data/Docker_Codebase/CalibNet/code/model_utils.py", line 42, in get_emd_loss
    matchl_out, matchr_out = tf_auctionmatch.auction_match(pred, gt)
  File "/data/Docker_Codebase/CalibNet/code/tf_ops/emd/tf_auctionmatch.py", line 20, in auction_match
    return auctionmatch_module.auction_match(xyz1,xyz2)
  File "<string>", line 37, in auction_match
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'AuctionMatch' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: AuctionMatch_1 = AuctionMatch[](map_1/TensorArrayStack_1/TensorArrayGatherV3, map_2/TensorArrayStack_1/TensorArrayGatherV3)]]
```

**Comment by epiception** [comment]
Are you running this on a CPU only version by any chance? You need to have a registered GPU to use the tensor ops. Also make sure you followed the steps to install the ops correctly. This should work on 1.3 as well. 1.4 onwards might have issues.

**Comment by krrish94** [comment]
And a common gotcha seems to be that one needs to ensure all Ops (from PointNet++) have been compiled correctly.

**Comment by ShreyasSkandan** [comment]
Right, I will try both these suggestions. Just fyi, i'm running Tensorflow that I installed using pip3

`
pip3 install tensorflow-gpu==1.3.0
`

**Comment by ShreyasSkandan** [comment]
I think my problem is because both my GPUs are of different architectures and with CUDA 8.0, tensorflow isn't able to detect and assign kernels to these GPUs correctly. I will try this on a machine with two Pascal GPUs and see if that helps. Thanks.

**Comment by krrish94** [comment]
@ShreyasSkandan Let us know if you have any further issues with getting the code to run. Closing this thread.
